# Generated by Django 4.1.4 on 2022-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcompra",
            name="valor_item",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Valor Item"
            ),
        ),
    ]
