# Generated by Django 4.1.4 on 2022-12-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="data_compra",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Compra"
            ),
        ),
    ]
