# Generated by Django 4.1.4 on 2022-12-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0002_compra_data_compra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compra",
            options={
                "ordering": ["-data_compra"],
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
            },
        ),
    ]
