# Generated by Django 4.1.4 on 2022-12-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0002_itemcompra_valor_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compra",
            options={
                "ordering": ["-id"],
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
            },
        ),
        migrations.AlterField(
            model_name="compra",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
    ]
