# Generated by Django 4.1.4 on 2022-12-31 20:57

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0004_alter_compra_data_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=stdimage.models.StdImageField(
                default="produtos/default.jpg",
                force_min_size=False,
                upload_to="produtos",
                variations={"thumbnail": {"crop": True, "height": 480, "width": 480}},
                verbose_name="Imagem",
            ),
        ),
    ]
