# Generated by Django 4.1.4 on 2023-01-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0006_alter_produto_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estoque",
            options={
                "ordering": ["-id"],
                "verbose_name": "Estoque",
                "verbose_name_plural": "Estoque",
            },
        ),
        migrations.AlterModelOptions(
            name="itemcompra",
            options={
                "ordering": ["-id"],
                "verbose_name": "Item Compra",
                "verbose_name_plural": "Itens Compra",
            },
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["-id"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.RemoveField(
            model_name="compra",
            name="valor_total",
        ),
    ]
