# Generated by Django 4.1.4 on 2023-01-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0007_alter_estoque_options_alter_itemcompra_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço"
            ),
        ),
    ]
