# Generated by Django 4.1.4 on 2022-12-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sintomas", models.TextField(verbose_name="Sintomas")),
                ("diagnostico", models.TextField(verbose_name="Diagnóstico")),
                ("tratamento", models.TextField(verbose_name="Tratamento")),
                ("data_consulta", models.DateField(verbose_name="Data da Consulta")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Valor Total"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pet",
                        verbose_name="Pet",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.veterinario",
                        verbose_name="Veterinário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-data_consulta"],
            },
        ),
        migrations.CreateModel(
            name="TipoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Serviço",
                "verbose_name_plural": "Tipos de Serviços",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_servico", models.DateField(verbose_name="Data do Serviço")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Valor Total"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pet",
                        verbose_name="Pet",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.tecnico",
                        verbose_name="Técnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["-data_servico"],
            },
        ),
        migrations.CreateModel(
            name="ItemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atendimento.servico",
                        verbose_name="Serviço",
                    ),
                ),
                (
                    "tipo_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atendimento.tiposervico",
                        verbose_name="Tipo de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Serviço",
                "verbose_name_plural": "Itens de Serviço",
            },
        ),
        migrations.CreateModel(
            name="ItemConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atendimento.consulta",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "tipo_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atendimento.tiposervico",
                        verbose_name="Tipo de Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Consulta",
                "verbose_name_plural": "Itens de Consulta",
            },
        ),
    ]
