# Generated by Django 4.1.4 on 2022-12-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta",
            options={
                "ordering": ["-data_consulta"],
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.AlterModelOptions(
            name="servico",
            options={
                "ordering": ["-data_servico"],
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
    ]
