# Generated by Django 4.1.4 on 2022-12-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cpf", models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "logradoro",
                    models.CharField(max_length=255, verbose_name="Logradoro"),
                ),
                ("cidade", models.CharField(max_length=255, verbose_name="Cidade")),
                ("uf", models.CharField(max_length=255, verbose_name="UF")),
                ("cep", models.CharField(max_length=255, verbose_name="CEP")),
                ("contato", models.CharField(max_length=255, verbose_name="Contato")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("raca", models.CharField(max_length=255, verbose_name="Raça")),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                ("sexo", models.CharField(max_length=255, verbose_name="Sexo")),
                ("especie", models.CharField(max_length=255, verbose_name="Espécie")),
                ("porte", models.CharField(max_length=255, verbose_name="Porte")),
                ("pelagem", models.CharField(max_length=255, verbose_name="Pelagem")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
    ]
