# Generated by Django 4.1.4 on 2023-01-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cliente_cidade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["-id"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="pet",
            options={
                "ordering": ["-id"],
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
    ]
