# Generated by Django 4.1.4 on 2022-12-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="salario",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="salário"
            ),
        ),
    ]
