# Generated by Django 4.1.4 on 2022-12-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_funcionario_salario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendente",
            name="cra",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CRA"
            ),
        ),
    ]
