# Generated by Django 4.1.4 on 2022-12-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_atendente_cra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="cpf",
            field=models.CharField(max_length=255, verbose_name="CPF"),
        ),
    ]
